from __future__ import division
from scipy.integrate import odeint
import matplotlib.pyplot as plt
import numpy

# This code is just for building the functions.

# The following function generates a sinuoidal voltage waveform for a paricular amplitude A volts and angular frequency w rad/sec
def voltage(A,w,t):
   return A*numpy.sin(w*t)

# The following function returns the derivative of the voltage waveform generated by the above function
def voltage_derivative(A,w,t):
   return w*A*numpy.cos(w*t)


# This function generates the waveform of net current flowing through a LC tank circuit for a sinusoidal input voltage of amplitude A and angular frequency w. Here L is the inductor value in Henry. C is the capacitor value in Farad. R1 is the ESR of inductor in ohm. R2 is the ESR of capacitor in ohm.
def response(A,w,L,R1,R2,C,t):

  def LC_tank_inductor(A,initial,t,w,L,R1):
     def tank_int1(i1,t):
         F1 = voltage(A,w,t)/L - (R1/L)*i1
         return F1
     i1 = odeint(tank_int1,initial,t)
     i1 = i1.flat
     return i1
   
  def LC_tank_capacitor(A,initial,t,w,C,R2):
     if R2==0:
         i2 = C*voltage_derivative(A,w,t)
         return i2
     else:
  
         def tank_int2(i2,t):
             F2 = voltage_derivative(A,w,t)/R2-i2/(R2*C)
             return F2
         i2 = odeint(tank_int2,initial,t)
         i2 = i2.flat
         return i2


  V = voltage(A,w,t)
  V = V.tolist()

  
  i1 = LC_tank_inductor(A,0,t,w,L,R1)
  i2 = LC_tank_capacitor(A,0,t,w,C,R2)
  
  i = []
  for j in range(len(t)):
     i.append(i1[j] + i2[j])

  Voltage_difference = 2*A
  gain = abs(max(i)-min(i))/Voltage_difference
  

  return i,V,t,gain # i is in Ampere, V is in volts, t is in seconds.


